app:
  env: prod # prod, stg, dev
  name: customapp-task

logging:
  level: debug
  is_prettified: true

adapters:
  redis:
    port: 6379
    db: 0
    pool:
      min_size: 5
      max_size: 15
      min_idle_size: 5
      max_idle_size: 10
      max_idle_time: 1h
    retries:
      attempts: 10
      interval: 2s

transports:
  http:
    host: 0.0.0.0
    port: 64333
